#!/usr/bin/env python3

import colors as c

print(c.random_color() + 'What is your name?')

name = input('==> ').title().strip()


while True:
    try:
        name = input('==>').strip().title()
    except (KeyboardInterrupt, EOFError):
        continue
    if name:
        break
    if not name:
        continue

print('Hello ' +name+ '!')


